pipeline {
    agent any

    environment {
        dockerImage = ''
        APP_NAME = 'kyb.blog'
        IMAGE_NAME = 'kybdev/blog-fe'
        IMAGE_TAG = "${env.BUILD_NUMBER}"

       DOCKER_CREDENTIALS_ID = 'docker-hub'
    }

    stages {
        stage('#Git-Clone') {
            steps {
                echo 'Cloning Repository'
                git url: 'https://github.com/WindowMania/blog-fe.git', branch: 'master', changelog: false
            }
            post {
                success {
                    echo 'Successfully Cloned Repository'
                }
                failure {
                    error 'This pipeline stops here...'
                }
            }
        }

        stage('#Bulid-Docker') {
            steps {
                echo 'Bulid Docker'
                script {
                    dockerImage = docker.build("${IMAGE_NAME}")
                }
            }
            post {
                failure {
                    error 'This pipeline stops here...'
                }
            }
        }

        stage('#Push-Docker') {
            steps {
                echo 'Push Docker'
                script {
                    docker.withRegistry('', DOCKER_CREDENTIALS_ID) {
                        dockerImage.push("${IMAGE_TAG}")
                        dockerImage.push("latest")
                    }
                }
            }
            post {
                success {
                    sh 'docker rmi $(docker images -q -f dangling=true) || true'
                }
                failure {
                    error 'This pipeline stops here...'
                }
            }
        }

    }

}